export const themes = [
    "light",
    "winter",
    "synthwave",
    "cyberpunk",
    "luxury",
    "business",
    "coffee",
    // "halloween",
    // "forest",
    // "aqua",
    // "black",
    // "night",
    // "sunset",
    // "dark",
    // "dracula",
    // "cupcake",
    // "bumblebee",
    // "emerald",
    // "corporate",
    // "retro",
    // "valentine",
    // "garden",
    // "lofi",
    // "pastel",
    // "fantasy",
    // "wireframe",
    // "cmyk",
    // "autumn",
    // "acid",
    // "lemonade",
    // "dim",
    // "nord",
];